#!/usr/bin/python
import TOSSIM
import sys
import random

from TOSSIM import *

t = TOSSIM.Tossim([])
r = t.radio()
t.addChannel("Query",sys.stdout);

r.add( int(1), int(2), float(0.0) )
r.add( int(2), int(1), float(-1.0) )

noise = open( "/opt/tinyos-2.1.2/tos/lib/tossim/noise/meyer-heavy.txt", "r" )

for line in noise:
	str1 = line.strip()
	if str1:
		val = int(str1)

		for i in range(1, 3):
			t.getNode(i).addNoiseTraceReading( val )

for i in range(1, 3):
	print( "Creating noise model for " + str(i) + "\n" );
	t.getNode(i).createNoiseModel()

for i in range(1,3):
	t.getNode(i).bootAtTime(0);

for i in range( 10000 ):
	t.runNextEvent()

